// Generated by delombok at Tue Nov 25 13:12:28 CET 2025
package com.example.domain;

import jakarta.persistence.Basic;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "comments")
public class Comment implements Serializable {

    @Id
    UUID id;

    @Basic(optional = false)
    private String content;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id")
    private Post post;

    private LocalDateTime createdAt;

    public Comment() {
    }

    public Comment(final UUID id, final String content, final Post post, final LocalDateTime createdAt) {
        this.id = id;
        this.content = content;
        this.post = post;
        this.createdAt = createdAt;
    }

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    public static class CommentBuilder {

        private UUID id;
        private String content;
        private Post post;
        private LocalDateTime createdAt;

        CommentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public Comment.CommentBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Comment.CommentBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Comment.CommentBuilder post(final Post post) {
            this.post = post;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Comment.CommentBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Comment build() {
            return new Comment(this.id, this.content, this.post, this.createdAt);
        }

        @Override
        public java.lang.String toString() {
            return "Comment.CommentBuilder(id=" + this.id + ", content=" + this.content + ", post=" + this.post + ", createdAt="
                    + this.createdAt + ")";
        }
    }

    public static Comment.CommentBuilder builder() {
        return new Comment.CommentBuilder();
    }

    public UUID getId() {
        return this.id;
    }

    public String getContent() {
        return this.content;
    }

    public Post getPost() {
        return this.post;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setId(final UUID id) {
        this.id = id;
    }

    public void setContent(final String content) {
        this.content = content;
    }

    public void setPost(final Post post) {
        this.post = post;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override

    public boolean equals(final Object o) {
        if (o == this) {
            return true;
        }
        if (!(o instanceof Comment)) {
            return false;
        }
        final Comment other = (Comment) o;
        if (!other.canEqual(this)) {
            return false;
        }
        final Object this$id = this.getId();
        final Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) {
            return false;
        }
        final Object this$content = this.getContent();
        final Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) {
            return false;
        }
        final Object this$post = this.getPost();
        final Object other$post = other.getPost();
        if (this$post == null ? other$post != null : !this$post.equals(other$post)) {
            return false;
        }
        final Object this$createdAt = this.getCreatedAt();
        final Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) {
            return false;
        }
        return true;
    }

    protected boolean canEqual(final Object other) {
        return other instanceof Comment;
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final Object $post = this.getPost();
        result = result * PRIME + ($post == null ? 43 : $post.hashCode());
        final Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @Override
    public java.lang.String toString() {
        return "Comment(id=" + this.getId() + ", content=" + this.getContent() + ", post=" + this.getPost() + ", createdAt="
                + this.getCreatedAt() + ")";
    }

}
