// Generated by delombok at Tue Nov 25 13:12:28 CET 2025
package com.example.domain;

import jakarta.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "comments")
public class Comment implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    UUID id;
    @Basic(optional = false)
    private String content;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id")
    private Post post;

    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")

    public static class CommentBuilder {
        @java.lang.SuppressWarnings("all")

        private UUID id;
        @java.lang.SuppressWarnings("all")

        private String content;
        @java.lang.SuppressWarnings("all")

        private Post post;
        @java.lang.SuppressWarnings("all")

        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")

        CommentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Comment.CommentBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Comment.CommentBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Comment.CommentBuilder post(final Post post) {
            this.post = post;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Comment.CommentBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")

        public Comment build() {
            return new Comment(this.id, this.content, this.post, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public java.lang.String toString() {
            return "Comment.CommentBuilder(id=" + this.id + ", content=" + this.content + ", post=" + this.post + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")

    public static Comment.CommentBuilder builder() {
        return new Comment.CommentBuilder();
    }

    @java.lang.SuppressWarnings("all")

    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")

    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")

    public Post getPost() {
        return this.post;
    }

    @java.lang.SuppressWarnings("all")

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")

    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")

    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")

    public void setPost(final Post post) {
        this.post = post;
    }

    @java.lang.SuppressWarnings("all")

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Comment)) return false;
        final Comment other = (Comment) o;
        if (!other.canEqual(this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$post = this.getPost();
        final java.lang.Object other$post = other.getPost();
        if (this$post == null ? other$post != null : !this$post.equals(other$post)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Comment;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $post = this.getPost();
        result = result * PRIME + ($post == null ? 43 : $post.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public java.lang.String toString() {
        return "Comment(id=" + this.getId() + ", content=" + this.getContent() + ", post=" + this.getPost() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")

    public Comment() {
    }

    @java.lang.SuppressWarnings("all")

    public Comment(final UUID id, final String content, final Post post, final LocalDateTime createdAt) {
        this.id = id;
        this.content = content;
        this.post = post;
        this.createdAt = createdAt;
    }
}
