// Generated by delombok at Tue Nov 25 13:12:28 CET 2025
package com.example.domain;

import jakarta.persistence.Basic;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "posts")
public class Post implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    UUID id;

    @Basic(optional = false)
    String title;

    @Basic(optional = false)
    String content;

    @Enumerated
    Status status;

    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    List<Comment> comments;

    LocalDateTime createdAt;
    LocalDateTime lastModifiedAt;

    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
        lastModifiedAt = createdAt;
    }

    @PreUpdate
    public void preUpdate() {
        lastModifiedAt = LocalDateTime.now();
    }

    @Override
    public String toString() {
        return "Post{" + "id=" + id + ", title=\'" + title + '\'' + ", content=\'" + content + '\'' + ", createdAt=" + createdAt
                + ", lastModifiedAt=" + lastModifiedAt + '}';
    }

    @java.lang.SuppressWarnings("all")

    private static Status $default$status() {
        return Status.DRAFT;
    }

    @java.lang.SuppressWarnings("all")

    public static class PostBuilder {
        @java.lang.SuppressWarnings("all")

        private UUID id;
        @java.lang.SuppressWarnings("all")

        private String title;
        @java.lang.SuppressWarnings("all")

        private String content;
        @java.lang.SuppressWarnings("all")

        private boolean status$set;
        @java.lang.SuppressWarnings("all")

        private Status status$value;
        @java.lang.SuppressWarnings("all")

        private List<Comment> comments;
        @java.lang.SuppressWarnings("all")

        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")

        private LocalDateTime lastModifiedAt;

        @java.lang.SuppressWarnings("all")

        PostBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder status(final Status status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder comments(final List<Comment> comments) {
            this.comments = comments;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")

        public Post.PostBuilder lastModifiedAt(final LocalDateTime lastModifiedAt) {
            this.lastModifiedAt = lastModifiedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")

        public Post build() {
            Status status$value = this.status$value;
            if (!this.status$set)
                status$value = Post.$default$status();
            return new Post(this.id, this.title, this.content, status$value, this.comments, this.createdAt, this.lastModifiedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")

        public java.lang.String toString() {
            return "Post.PostBuilder(id=" + this.id + ", title=" + this.title + ", content=" + this.content + ", status$value="
                    + this.status$value + ", comments=" + this.comments + ", createdAt=" + this.createdAt + ", lastModifiedAt="
                    + this.lastModifiedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")

    public static Post.PostBuilder builder() {
        return new Post.PostBuilder();
    }

    @java.lang.SuppressWarnings("all")

    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")

    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")

    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")

    public Status getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")

    public List<Comment> getComments() {
        return this.comments;
    }

    @java.lang.SuppressWarnings("all")

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")

    public LocalDateTime getLastModifiedAt() {
        return this.lastModifiedAt;
    }

    @java.lang.SuppressWarnings("all")

    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")

    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")

    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")

    public void setStatus(final Status status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")

    public void setComments(final List<Comment> comments) {
        this.comments = comments;
    }

    @java.lang.SuppressWarnings("all")

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")

    public void setLastModifiedAt(final LocalDateTime lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public boolean equals(final java.lang.Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Post))
            return false;
        final Post other = (Post) o;
        if (!other.canEqual(this))
            return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id))
            return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title))
            return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content))
            return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status))
            return false;
        final java.lang.Object this$comments = this.getComments();
        final java.lang.Object other$comments = other.getComments();
        if (this$comments == null ? other$comments != null : !this$comments.equals(other$comments))
            return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt))
            return false;
        final java.lang.Object this$lastModifiedAt = this.getLastModifiedAt();
        final java.lang.Object other$lastModifiedAt = other.getLastModifiedAt();
        if (this$lastModifiedAt == null ? other$lastModifiedAt != null : !this$lastModifiedAt.equals(other$lastModifiedAt))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Post;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $comments = this.getComments();
        result = result * PRIME + ($comments == null ? 43 : $comments.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $lastModifiedAt = this.getLastModifiedAt();
        result = result * PRIME + ($lastModifiedAt == null ? 43 : $lastModifiedAt.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")

    public Post() {
        this.status = Post.$default$status();
    }

    @java.lang.SuppressWarnings("all")

    public Post(final UUID id, final String title, final String content, final Status status, final List<Comment> comments,
            final LocalDateTime createdAt, final LocalDateTime lastModifiedAt) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.status = status;
        this.comments = comments;
        this.createdAt = createdAt;
        this.lastModifiedAt = lastModifiedAt;
    }
}
